#!/usr/bin/env bash
#
# Little script to apply a patch hosted on the web
#
# Copyright (C) 2017 Giuseppe "joe2k01" Barillari
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>

version() {
	echo "Git WebApply beta 1"
	echo "My first try with git plugins"
}

usage() {
	echo "-h: Prints this"
	echo "-v: Verbose "
	echo "$0 [options] [url]"
}

apply() {

	case $2 in
		1)
			wget $1 -O webapply.patch &&
			git apply -v webapply.patch &&
			rm webapply.patch &&
			exit 0
		;;
		0)
			wget -q $1 -O webapply.patch &&
			git apply webapply.patch &&
			rm webapply.patch &&
			exit 0
		;;
	esac

}

case "$1" in
	"-h")
		usage
		exit 0
	;;
	"-v")
		apply "$2" 1
	;;
	*)
		apply "$1" 0
	;;
esac
