#!/usr/bin/env bash
#
# Little script to compile my custom Android Kernel(s)
#
# Copyright (C) 2017 Giuseppe "joe2k01" Barillari
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>

# Start the whole stuff with a nice help function
function h() {
	echo -e ""
	echo -e "${BOLD}How to use:${RST} ./${0#./} device\n"
	exit
}

if [ -z "$1" ]; then
	echo -e "Specify a device"
	exit
else
	if [ "$1" == "gts210vewifi" ] || [ "$1" == "hammerheadcaf" ]; then
		echo -e " "
	else
		echo -e "$1 is not supported"
		exit
	fi
fi
