#!/usr/bin/env bash
#
# Little set of tools to make easier working with git and Kernel
#
# Copyright (C) 2017 Giuseppe "joe2k01" Barillari
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>

# ccache
export CCACHE_DIR="/home/joe2k01/.ccachehh"
export CC="ccache gcc"
export CXX="ccache g++"
export PATH="/usr/lib/ccache:$PATH"

# Quick theirs checkout
ch() {
    git checkout --theirs "$1" && git add . && git commit
}

# Quick HEAD rebase
reb() {
    git rebase -i HEAD^
}

# Quick ours checkout
ou() {
    git checkout --ours "$1" && git add . && git reset
}
